# Generated by Django 6.0.3 on 2026-03-15 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_transaccion_remitente_alter_transaccion_destinatario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='banco',
            field=models.CharField(default='No especificado', max_length=100),
        ),
        migrations.AddField(
            model_name='contacto',
            name='email',
            field=models.EmailField(default='sin-correo@correo.com', max_length=254),
        ),
    ]
