# Generated by Django 6.0.3 on 2026-03-15 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_contacto_banco_contacto_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='documento',
            field=models.CharField(default='Sin RUT', max_length=12),
        ),
        migrations.AddField(
            model_name='contacto',
            name='tipo_cuenta',
            field=models.CharField(default='No especificado', max_length=50),
        ),
    ]
