# Generated by Django 6.0.3 on 2026-03-16 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_contacto_documento_contacto_tipo_cuenta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='monto',
            field=models.DecimalField(decimal_places=2, default=100000, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='monto',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
