# Generated by Django 6.0.3 on 2026-03-16 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_balance_monto_alter_transaccion_monto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaccion',
            old_name='remitente',
            new_name='emisor',
        ),
        migrations.RenameField(
            model_name='transaccion',
            old_name='destinatario',
            new_name='receptor',
        ),
        migrations.RemoveField(
            model_name='transaccion',
            name='usuario',
        ),
    ]
